### ISSUE TITLE
error: conversion from 'int' to 'QChar' is ambiguous

### ISSUE THREAD

**Issue by otonoton** [KDAB/KDMacTouchBar#5]
I have a 2022 M2 MBP with the touch bar. I'm getting this error trying to compile with Qt 6.5.0 on Ventura with 13.1 SDK:

```
kdmactouchbar.mm:78:41: error: conversion from 'int' to 'QChar' is ambiguous
    QString returnText(original.size(), 0);
                                        ^
```

Including several warnings about deprecated constructors (QMouseEvent) and functions (QAction::associatedWidgets).

If I change that 0 to `QChar(0)`, I get another error:

```
mainwindow.cpp:25:10: fatal error: 'QtWidgets/QAction' file not found
#include <QtWidgets/QAction>
         ^~~~~~~~~~~~~~~~~~~
mainwindow.cpp:25:10: note: did not find header 'QAction' in framework 'QtWidgets' (loaded from '/Users/user/Qt6/6.5.0/macos/lib')
```

**Comment by cschleifenbaum** [comment]
@otonoton Thank you for your input. I've created a new release: https://github.com/KDAB/KDMacTouchBar/releases/tag/v1.1.3
